name: "Cache and Generate Orval APIs"
description: "Caches Orval files and regenerates APIs if the cache is missing."
author: "Adam Rzymski"
inputs:
  working-directory:
    description: "Working directory for Orval commands."
    required: true
  api-path:
    description: "Path to the API files to cache."
    required: true
  swagger-path:
    description: "Path to swagger files for hashing the cache key."
    required: true
  orval-config:
    description: "Path to the Orval configuration file."
    required: true

runs:
  using: "composite"
  steps:
    # - name: 📥 Checkout Code
    #   uses: actions/checkout@v4

    - name: 📂 Create API Directory
      run: |
        #  Create the API directory if it doesn't exist in powershell
        if (!(Test-Path -Path ${{ inputs.api-path }})) {
          New-Item -Path ${{ inputs.api-path }} -ItemType Directory
        }
      shell: powershell

    - name: 📦 Cache Orval Files
      id: cache-orval-files
      uses: ./../../../_actions/CacheWith7z/v1.0.4
      with:
        path: ${{ inputs.api-path }}
        key: ${{ runner.os }}-orval-${{ hashFiles(inputs.swagger-path, inputs.orval-config) }}
        restore-keys: |
          ${{ runner.os }}-orval-

    - name: 🛠️ Generate APIs with Orval
      if: steps.cache-orval-files.outputs.cache-hit != 'true'
      run: npm run orval:cache
      shell: powershell
      working-directory: ${{ inputs.working-directory }}
